name = "12bet"
main = "../12BET/worker.js"
compatibility_date = "2023-10-23"

account_id = "b3fa92a12b796d7f8b9b52e1b4e196a2"
workers_dev = false
route = { pattern = "nnaoxiang.com/*", zone_name = "nnaoxiang.com" }