name = "manbet"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "b3fa92a12b796d7f8b9b52e1b4e196a2"
workers_dev = false
routes = [
#{ pattern = "2211299.com/*", zone_name = "2211299.com" },
#{ pattern = "atgarrison.com/*", zone_name = "atgarrison.com" },
#{ pattern = "www.ban-qian.com/*", zone_name = "ban-qian.com" },
#{ pattern = "coinbest.info/*", zone_name = "coinbest.info" },
#{ pattern = "dylannelee.com/*", zone_name = "dylannelee.com" },
#{ pattern = "fordongli.com/*", zone_name = "fordongli.com" },
#{ pattern = "www.gyytgd.com/*", zone_name = "gyytgd.com" },
#{ pattern = "www.kairuihrb.com/*", zone_name = "kairuihrb.com" },
#{ pattern = "lifw.org/*", zone_name = "lifw.org" },
#{ pattern = "magnets-fasts.com/*", zone_name = "magnets-fasts.com" },
#{ pattern = "mikecat.net/*", zone_name = "mikecat.net" },
#{ pattern = "www.mrdaydreamer.com/*", zone_name = "mrdaydreamer.com" },
#{ pattern = "www.nipponexpress-group.com/*", zone_name = "nipponexpress-group.com" },
#{ pattern = "s1s2.biz/*", zone_name = "s1s2.biz" },
#{ pattern = "samarestudio.com/*", zone_name = "samarestudio.com" },
#{ pattern = "sloger.info/*", zone_name = "sloger.info" },
#{ pattern = "soitsgray.com/*", zone_name = "soitsgray.com" },
#{ pattern = "tchaoda888.com/*", zone_name = "tchaoda888.com" },
#{ pattern = "tomohironishimura.com/*", zone_name = "tomohironishimura.com" },
#{ pattern = "www.www10www.com/*", zone_name = "www10www.com" },
#{ pattern = "xinhuiwen.com/*", zone_name = "xinhuiwen.com" },
#{ pattern = "www.zcjingongjx.com/*", zone_name = "zcjingongjx.com" },
#{ pattern = "www.zdzpx.com/*", zone_name = "zdzpx.com" },
]