name = "w88y"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "b3fa92a12b796d7f8b9b52e1b4e196a2"
workers_dev = false
routes = [
#{ pattern = "520vzr.com/*", zone_name = "520vzr.com" },
#{ pattern = "mtl026.com/*", zone_name = "mtl026.com" },
#{ pattern = "phyxp.com/*", zone_name = "phyxp.com" },
#{ pattern = "rdyxr.com/*", zone_name = "rdyxr.com" },
#{ pattern = "vdnkd.com/*", zone_name = "vdnkd.com" },
#{ pattern = "vvyyw.com/*", zone_name = "vvyyw.com" },
#{ pattern = "xvjxv.com/*", zone_name = "xvjxv.com" }

]