name = "m88"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "b3fa92a12b796d7f8b9b52e1b4e196a2"
workers_dev = false
routes = [ { pattern = "028bird.com/*", zone_name = "028bird.com" },
{ pattern = "0871365.net/*", zone_name = "0871365.net" },
{ pattern = "www.520banjia.com/*", zone_name = "520banjia.com" },
{ pattern = "www.86yuesao.com/*", zone_name = "86yuesao.com" },
{ pattern = "agrichina-expo.com/*", zone_name = "agrichina-expo.com" },
{ pattern = "aibaifang.com/*", zone_name = "aibaifang.com" },
{ pattern = "dmkjw.com/*", zone_name = "dmkjw.com" },
{ pattern = "eyxs.net/*", zone_name = "eyxs.net" },
{ pattern = "gsrcw.net/*", zone_name = "gsrcw.net" },
{ pattern = "www.gwyxx.com/*", zone_name = "gwyxx.com" },
{ pattern = "gxboquan.com/*", zone_name = "gxboquan.com" },
{ pattern = "gzjianyue.com/*", zone_name = "gzjianyue.com" },
{ pattern = "www.hanshuangxuebing.com/*", zone_name = "hanshuangxuebing.com" },
{ pattern = "www.hnqhjd168.com/*", zone_name = "hnqhjd168.com" },
{ pattern = "www.hongyinyoga.com/*", zone_name = "hongyinyoga.com" },
{ pattern = "huajieyl.com/*", zone_name = "huajieyl.com" },
{ pattern = "www.huojiguang.com/*", zone_name = "huojiguang.com" },
{ pattern = "www.ip-link.net/*", zone_name = "ip-link.net" },
{ pattern = "ir-lab.org/*", zone_name = "ir-lab.org" },
{ pattern = "www.jhksdq.com/*", zone_name = "jhksdq.com" },
{ pattern = "www.jiachenggo.com/*", zone_name = "jiachenggo.com" },
{ pattern = "www.jinanyizhen.com/*", zone_name = "jinanyizhen.com" },
{ pattern = "www.jinruilanmei.com/*", zone_name = "jinruilanmei.com" },
{ pattern = "jnzhentan.net/*", zone_name = "jnzhentan.net" },
{ pattern = "jsakdq.com/*", zone_name = "jsakdq.com" },
{ pattern = "www.ka-dun.com/*", zone_name = "ka-dun.com" },
{ pattern = "www.keyleadchina.com/*", zone_name = "keyleadchina.com" },
{ pattern = "www.lyshanzhagan.com/*", zone_name = "lyshanzhagan.com" },
{ pattern = "www.lyyaoqiang.com/*", zone_name = "lyyaoqiang.com" },
{ pattern = "www.mrytgc.net/*", zone_name = "mrytgc.net" },
{ pattern = "nicklas-bendtner.com/*", zone_name = "nicklas-bendtner.com" },
{ pattern = "www.owddc.com/*", zone_name = "owddc.com" },
{ pattern = "oyjcgs.com/*", zone_name = "oyjcgs.com" },
{ pattern = "www.qnsphoto.com/*", zone_name = "qnsphoto.com" },
{ pattern = "www.rqlnd.com/*", zone_name = "rqlnd.com" },
{ pattern = "www.sdydgd.com/*", zone_name = "sdydgd.com" },
{ pattern = "sgymj.com/*", zone_name = "sgymj.com" },
{ pattern = "www.shuangkeqingxi.com/*", zone_name = "shuangkeqingxi.com" },
{ pattern = "songtaokaisuo.com/*", zone_name = "songtaokaisuo.com" },
{ pattern = "www.swd-hh.com/*", zone_name = "swd-hh.com" },
{ pattern = "teqp.net/*", zone_name = "teqp.net" },
{ pattern = "tswj.net/*", zone_name = "tswj.net" },
{ pattern = "ux-v.com/*", zone_name = "ux-v.com" },
{ pattern = "wumeicleaning.com/*", zone_name = "wumeicleaning.com" },
{ pattern = "ybhundun.com/*", zone_name = "ybhundun.com" },
{ pattern = "www.yllch.com/*", zone_name = "yllch.com" },
{ pattern = "yxlshy.com/*", zone_name = "yxlshy.com" },
{ pattern = "zhonggongguoji.com/*", zone_name = "zhonggongguoji.com" },
{ pattern = "zhuzhiyishi.net/*", zone_name = "zhuzhiyishi.net" },
{ pattern = "zjlssc.com/*", zone_name = "zjlssc.com" },
{ pattern = "www.zspinquan.com/*", zone_name = "zspinquan.com" },
{ pattern = "www.zzhwtravel.com/*", zone_name = "zzhwtravel.com" },
]
