name = "m88"
main = "../worker.js"
compatibility_date = "2023-10-23"

account_id = "b3fa92a12b796d7f8b9b52e1b4e196a2"
workers_dev = false
route = { pattern = "028bird.com/*", zone_name = "028bird.com" }
route = { pattern = "0871365.net/*", zone_name = "0871365.net" }
route = { pattern = "520banjia.com/*", zone_name = "520banjia.com" }
route = { pattern = "www.86yuesao.com/*", zone_name = "86yuesao.com" }
route = { pattern = "www.agrichina-expo.com/*", zone_name = "agrichina-expo.com" }
route = { pattern = "aibaifang.com/*", zone_name = "aibaifang.com" }
route = { pattern = "dmkjw.com/*", zone_name = "dmkjw.com" }
route = { pattern = "eyxs.net/*", zone_name = "eyxs.net" }
route = { pattern = "gsrcw.net/*", zone_name = "gsrcw.net" }
route = { pattern = "www.gwyxx.com/*", zone_name = "gwyxx.com" }
route = { pattern = "gxboquan.com/*", zone_name = "gxboquan.com" }
route = { pattern = "gzjianyue.com/*", zone_name = "gzjianyue.com" }
route = { pattern = "www.hanshuangxuebing.com/*", zone_name = "hanshuangxuebing.com" }
route = { pattern = "www.hnqhjd168.com/*", zone_name = "hnqhjd168.com" }
route = { pattern = "www.hongyinyoga.com/*", zone_name = "hongyinyoga.com" }
route = { pattern = "huajieyl.com/*", zone_name = "huajieyl.com" }
route = { pattern = "www.huojiguang.com/*", zone_name = "huojiguang.com" }
route = { pattern = "www.ip-link.net/*", zone_name = "ip-link.net" }
route = { pattern = "ir-lab.org/*", zone_name = "ir-lab.org" }
route = { pattern = "www.jhksdq.com/*", zone_name = "jhksdq.com" }
route = { pattern = "www.jiachenggo.com/*", zone_name = "jiachenggo.com" }
route = { pattern = "www.jinanyizhen.com/*", zone_name = "jinanyizhen.com" }
route = { pattern = "www.jinruilanmei.com/*", zone_name = "jinruilanmei.com" }
route = { pattern = "jnzhentan.net/*", zone_name = "jnzhentan.net" }
route = { pattern = "jsakdq.com/*", zone_name = "jsakdq.com" }
route = { pattern = "www.ka-dun.com/*", zone_name = "ka-dun.com" }
route = { pattern = "www.keyleadchina.com/*", zone_name = "keyleadchina.com" }
route = { pattern = "www.lyshanzhagan.com/*", zone_name = "lyshanzhagan.com" }
route = { pattern = "www.lyyaoqiang.com/*", zone_name = "lyyaoqiang.com" }
route = { pattern = "www.mrytgc.net/*", zone_name = "mrytgc.net" }
route = { pattern = "nicklas-bendtner.com/*", zone_name = "nicklas-bendtner.com" }
route = { pattern = "www.owddc.com/*", zone_name = "owddc.com" }
route = { pattern = "oyjcgs.com/*", zone_name = "oyjcgs.com" }
route = { pattern = "www.qnsphoto.com/*", zone_name = "qnsphoto.com" }
route = { pattern = "www.rqlnd.com/*", zone_name = "rqlnd.com" }
route = { pattern = "www.sdydgd.com/*", zone_name = "sdydgd.com" }
route = { pattern = "sgymj.com/*", zone_name = "sgymj.com" }
route = { pattern = "www.shuangkeqingxi.com/*", zone_name = "shuangkeqingxi.com" }
route = { pattern = "songtaokaisuo.com/*", zone_name = "songtaokaisuo.com" }
route = { pattern = "www.swd-hh.com/*", zone_name = "swd-hh.com" }
route = { pattern = "teqp.net/*", zone_name = "teqp.net" }
route = { pattern = "tswj.net/*", zone_name = "tswj.net" }
route = { pattern = "ux-v.com/*", zone_name = "ux-v.com" }
route = { pattern = "wumeicleaning.com/*", zone_name = "wumeicleaning.com" }
route = { pattern = "ybhundun.com/*", zone_name = "ybhundun.com" }
route = { pattern = "www.yllch.com/*", zone_name = "yllch.com" }
route = { pattern = "yxlshy.com/*", zone_name = "yxlshy.com" }
route = { pattern = "zhonggongguoji.com/*", zone_name = "zhonggongguoji.com" }
route = { pattern = "zhuzhiyishi.net/*", zone_name = "zhuzhiyishi.net" }
route = { pattern = "zjlssc.com/*", zone_name = "zjlssc.com" }
route = { pattern = "www.zspinquan.com/*", zone_name = "zspinquan.com" }
route = { pattern = "www.zzhwtravel.com/*", zone_name = "zzhwtravel.com" }
